apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-purpose
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default # Must match the metadata.name of your NodeClass

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-family"
          operator: In
          values: ["m6a", "m5", "r6a", "r5"] # Force Memory-balanced families
        - key: "node.kubernetes.io/instance-size"
          operator: NotIn
          values: ["medium", "large"] # Force at least xlarge (usually 16GB+ RAM)

      # Optional: Expire nodes after 2 weeks to keep them fresh
      expireAfter: 336h

      minValues:
        - key: "karpenter.sh/capacity-type" # Or use instance-family
          operator: In
          values: [ "on-demand" ]
          minValues: 3  # <--- Keeps 3 nodes "warm" at all times

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m