apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-purpose
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default # Must match the metadata.name of your NodeClass

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["m5.xlarge", "m5.2xlarge", "r5.xlarge"]

      # Optional: Expire nodes after 2 weeks to keep them fresh
      expireAfter: 336h

  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 1m