apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-purpose
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default # Must match the metadata.name of your NodeClass

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "eks.amazonaws.comi/nstance-family"
          operator: In
          values: ["m5a", "m6a", "r5a", "r6a", "c6a"]
        - key: "eks.amazonaws.com/instance-size"
          operator: In # Using 'In' is more reliable than 'NotIn' for the controller
          values: ["xlarge", "2xlarge", "4xlarge", "8xlarge"]
            # Optional: Expire nodes after 2 weeks to keep them fresh

      expireAfter: 336h

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m